project_name: orgalorg
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -mod=readonly
checksum:
  name_template: 'sha256sums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
